apiVersion: v1
kind: Service
metadata:
  name: app-spring-eureka-server-service
spec:
  type: LoadBalancer
  ports:
  - port: 8761
  selector:
    app: app-spring-eureka-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-spring-eureka-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-spring-eureka-server
  template:
    metadata:
      labels:
        app: app-spring-eureka-server
    spec:
      containers:
      - name: spring-cloud-registry-eureka-server
        image: spring-cloud-registry-eureka-server:v1
        ports:
        - containerPort: 8761

# kubectl create -f kube-deployment-service.yml